# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins_dir:      plugins

gems:            [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            More than seven
tagline:          'Gareth Rushgrove'
description:      'Writing about code. Occasional other topics. Made by <a href="https://twitter.com/garethr">@garethr</a>.'
url:              http://www.morethanseven.net
baseurl:          /

author:
  name:           'Gareth Rushgrove'
  url:            https://twitter.com/garethr

paginate:         5

google_analytics_tracking_id: UA-435455-1
